"""create node executions table

Revision ID: 8132ffd9de48
Revises: b23414e2b0a7
Create Date: 2026-08-24 17:55:31.731426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8132ffd9de48'
down_revision: Union[str, Sequence[str], None] = 'b23414e2b0a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_executions',
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', name='nodeexecutionstatus'), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['workflow_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_executions_execution_id'), 'node_executions', ['execution_id'], unique=False)
    op.create_index(op.f('ix_node_executions_node_id'), 'node_executions', ['node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_executions_node_id'), table_name='node_executions')
    op.drop_index(op.f('ix_node_executions_execution_id'), table_name='node_executions')
    op.drop_table('node_executions')
    # ### end Alembic commands ###
