"""add attempt to node executions

Revision ID: b011bfc671bb
Revises: b8939c566bab
Create Date: 2026-09-16 12:43:54.234287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b011bfc671bb'
down_revision: Union[str, Sequence[str], None] = 'b8939c566bab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_executions', sa.Column('attempt', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node_executions', 'attempt')
    # ### end Alembic commands ###
