"""add branch to workflow edges

Revision ID: fb939ff4ad15
Revises: 8132ffd9de48
Create Date: 2026-08-25 23:55:30.477540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb939ff4ad15'
down_revision: Union[str, Sequence[str], None] = '8132ffd9de48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_edges', sa.Column('branch', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_edges', 'branch')
    # ### end Alembic commands ###
